name: Create PR to TestPR

on:
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: Florian  # Checkout de la branche Florian

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create PR
        run: |
          git checkout -b pr-to-testpr-${GITHUB_RUN_NUMBER}
          git push --set-upstream origin pr-to-testpr-${GITHUB_RUN_NUMBER}

          # Créer la PR en utilisant l'API GitHub
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "{\"title\":\"Déclenchement manuel PR from Florian to TestPR\",\"head\":\"Florian\",\"base\":\"TestPR\"}"

          git checkout Florian 
          git branch -D pr-to-testpr-${GITHUB_RUN_NUMBER}  
