name: Create PR to TestPR2

on:
  workflow_dispatch: # Déclenchement manuel depuis l'interface GitHub

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create PR to TestPR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout Florian
          git pull origin Florian
          git checkout -b pr-to-testpr-${GITHUB_RUN_NUMBER}
          git push --set-upstream origin pr-to-testpr-${GITHUB_RUN_NUMBER}

          hub pull-request \
            --base TestPR \
            --head pr-to-testpr-${GITHUB_RUN_NUMBER} \
            --title "Manual PR from Florian to TestPR" \
            --body "Manually triggered PR from Florian to TestPR"

          git checkout Florian
          git branch -D pr-to-testpr-${GITHUB_RUN_NUMBER}