name: Create PR to prod

on:
  workflow_dispatch:
    inputs:
      pr_prefix:
        description: 'Prefix for PR title (e.g., Majeur, Mineur, Patch)'
        required: true
        default: 'Majeur'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main  # Checkout de la branche main

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create PR
        run: |
          # Créer la PR en utilisant l'API GitHub
          curl \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "{\"title\":\"${{ github.event.inputs.pr_prefix }} - Manual PR from main to prod\",\"head\":\"main\",\"base\":\"prod\"}"